http:
  listener:
    host: "localhost"
    port: "8085"
  requester:
    TravelOnTip:
      host: "localhost"
      port: "8083"
      routesPath: "/travel-on-tip/routes"
      schedulesPath: "/travel-on-tip/schedules"
    FastGo:
       host: "localhost"
       port: "8084"
       routespath: "/fastGo/routes"
       schedulespath: "/fastGo/schedules"